<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0H07TE8" ignored="1" name="TestGroup2" tests="10" failures="1" timestamp="31 Mar 2020 09:33:33 GMT" time="44.906" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Assert cannot be resolved
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Assert cannot be resolved

at Remote.RL_DemoDataProvider.afterMethod(RL_DemoDataProvider.java:41)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="f" time="36.213" classname="Remote.RL_DemoDataProvider"/>
  <testcase name="f" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.0" classname="Remote.RL_DemoDataProvider">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.001" classname="Remote.CaseStudyReg"/>
  <testcase name="google" time="0.001" classname="Remote.FirstTestNGDemo"/>
  <testcase name="Instagram" time="0.002" classname="Remote.FirstTestNGDemo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Remote.FirstTestNGDemo.Instagram(FirstTestNGDemo.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Instagram -->
  <testcase name="twitter" time="0.0" classname="Remote.FirstTestNGDemo">
    <skipped/>
  </testcase> <!-- twitter -->
  <testcase name="Facebook" time="0.007" classname="Remote.FirstTestNGDemo"/>
  <testcase name="whatsapp" time="0.0" classname="Remote.FirstTestNGDemo">
    <ignored/>
  </testcase> <!-- whatsapp -->
</testsuite> <!-- TestGroup2 -->
